name: bonemapping
channels:
  - nvidia
  - conda-forge
  - anaconda
  - intel
  - defaults
  - plotly
  - numba
dependencies:
  - cython
  - dataclasses
  - h5py
  - intel-openmp
  - intelpython
  - loguru
  - matplotlib-base
  - meshio
  - numba
  - numexpr
  - numpy
  - pandas
  - pip
  - plotly
  - plotly_express
  - pydicom
  - pyntcloud
  - pyqt
  - pyqtchart
  - pyside2
  - python=3.10.6
  - pyvista
  - pyvistaqt
  - scipy
  - snakeviz
  - tqdm
  - trimesh
  - pip:
      - ansys-mapdl-reader