integration:
  method: E # equivalent to BoneMat V3. Only implementation currently
  steps: 4
  apply_elasticity_bounds: false
CT_Calibration:
  ct_coefs: # (a, b, c, ... n in rho_QCT = a + b*HU + c*HU^2...) where x is HU.
  - 0.056148 # a
  - 0.007764 # b
  - 0 # c. Can be deleted or zeroed to ignore
  apply_ash_correction: true
  ash_correction_coefs: # (a, b, c, ... n in y = a + bx + cx2..) where x is rho_QCT
    - 0.0789
    - 0.877
  min_rho: 1.0e-06 # densities below this are assumed to be equal to minVal
  min_modulus_value: 1e-6
  max_modulus_value: 1E6
  modulus_bin_grouping_method: max  # assign the mean or max modulus in bin to all elements in modulus bin
  modulus_bin_size: 1  # Material step size definition
  modulus_coefs: # (a, b, c in E = a + b*rho^i2)
  - 0  # a
  - 6.95 # b
  modulus_exponent: 1.49 # exponent for modulus equation.
  poisson: 0.35 # poisson's ratio to use for bone in the model
